Associations setup
afizsavage/school-library pull request #3
Opened 2022-03-18 16:11 UTC by afizsavage

- Create classes with the following names: Classroom, Books, and Rental
- Create the has-many/belongs-to relationship between Classroom and Student classes
- Create the many-to-many (also has-many-through) relationship between Person and Book using the intermediate class Rental

2022-03-18 17:04 UTC, Emmyn5600 requested changes
Hi @afizsavage 

Good job so far! I know you have worked hard on making this milestone But  There are some issues that you still need to work on to go to the next project but you are almost there!

## To highlight :champagne:

- All linters are passing :heavy_check_mark:
- Good commit history :heavy_check_mark:
- Good PR description :heavy_check_mark:
- The database is well structured/created. :heavy_check_mark:

## Required Changes :recycle:

- [ ] Check the comment under the review

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!:clap::clap::clap:

#### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
#### **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-18 17:04 UTC, Emmyn5600 commented on rental.rb
> +  attr_reader :book, :person
- [ ] Book and person has to be the attr_accessor, not attr_reader.

2022-03-18 17:04 UTC, Emmyn5600 commented on rental.rb
> +  end
- [ ] The above implementation was correct to add or push both book and person.

2022-03-18 17:04 UTC, Emmyn5600 commented on book.rb
> +  attr_reader :rentals
- [ ] rentals have to be attr_accessor too.

- [ ] From the def add_rental implementation, you have to implement it in the below one.

```ruby
  def add_rental(person, date)
    # *the book itself should be sent as a parameter to create the new rental achieving the 'has-many' association. 
    Rental.new(date, self, person)
  end
```

2022-03-18 17:53 UTC, mmsesay requested changes
Hi @afizsavage, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-18 17:53 UTC, mmsesay commented on person.rb
> +  def add_rental(_rental)
- [ ] I got an error when I tried to add a rental for a person. This method should take to arguments, `book` & `date`. As of now, your method only takes one argument. And when I pass the one argument, it also throw an error.

See screenshots:

With two arguments passed|
:--------------------------------------:|
![a1](https://user-images.githubusercontent.com/39523312/159056855-e85dc120-f17f-47b8-b5d4-dc4eeb95d9b3.png)

With one argument passed|
:-----------------------------------:|
![a1](https://user-images.githubusercontent.com/39523312/159056972-c7737e61-26b7-468e-b4ce-b02cae0cf0ee.png)

2022-03-19 10:27 UTC, FrederickMih approved these changes
# Status: Approved :tada: 
![Approved](https://user-images.githubusercontent.com/63087491/159117370-d9175ec9-915e-4b7f-a6da-9446c422ec2f.jpg)



Hi @afizsavage , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-19 10:45 UTC, merged